'''print("04 Feb")
a=16
b=8
print(a&b)
print(a|b)
print(a>>2)
print(b<<2)
print(a^8)
a=input("Total Value:")
print(a)
print(type(a))
b=int(a)
print(b)
print(type(b))
c=float(a)
print(c)
print(type(c))
d=complex(a)
print(d)
print(type(d))
a=input("Enter Any Value:")
print(a)
b=int(a)
print(b)
print(b+10)
print(b-5)
print(b*2)
print(b/4)
print(b%8)
print(b**2)
print(b//6)
x=input("a=")
print(x)
y=float(x)
print(y)
print(y+9)
print(y-2)
print(y*5)
print(y/2)
print(y%4)
print(y**3)
print(y//8)
'''
x="Devadarshini"
print(x[4:9])
print(x[0:-3:2])
print(x[-2:-9])
Hint=" HAppY New YeAr tO AlL  "
print(Hint.upper())
print(Hint.lower())
print(Hint.title())
print(Hint.swapcase())
print(Hint.capitalize())
print(Hint.strip())
print(Hint.rstrip())
print(Hint.lstrip())
print(len(Hint))
print(Hint.count("e"))
print(Hint.index("p"))
print(Hint.find("A"))
print(Hint.isalpha())
print(Hint.isdigit())
print(Hint.islower())
print(Hint.isupper())

a="12937834"
print(a.isdigit())
print(a.find("3"))

a='PrintThaTopictoand'
print(a.replace("a","e"))

x="Hello"
y="My Friend"
z=x+y
print(z)
print(x+"-"+y)
print(z.split(","))
print(x+" "+y)

